controller:
  installPlugins:
    - kubernetes:1.29.0
    - workflow-aggregator:2.6
    - git:4.10.1
  service:
    type: NodePort
    port: 8080
  persistence:
    enabled: true
    existingClaim: jenkins-pvc
    storageClass: ""
    size: 20Gi