controller:
  installPlugins:
    - kubernetes:1.29.0
    - workflow-aggregator:2.6
    - git:4.10.1
  service:
    type: ClusterIP
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  persistence:
    enabled: true
    existingClaim: jenkins-pvc
    storageClass: ""
    size: 10Gi
  serviceAccount:
    create: true
    name: default
